# training hyperparameters
lr: 0.0002
num_epochs: 200
# architectural 
embedding_dim: 128
encoder_pretrained: true
dense_hidden_dim: 128
use_attention: true
use_gated: true
# data settings
batch_accum_iters: 2
label_scheme_name: mild_mod
num_classes: 3
view: plaxpsax
view_scheme_name: three_class
# program setting
log_dir: ../logs
mode: test
model_load_dir: grateful-universe-4
use_cuda: true
use_wandb: false
